### ISSUE TITLE
Can't build on Render.com

### ISSUE THREAD

**Issue by Kezanwar** [mstephen19/nanolith#64]
**Describe the bug**
Hello,

I am using the Nanolith pkg to spawn a thread using worker.launchService({}) syntax to do some expensive computation for me on a separate thread. 

It works fine on my local machine (macbook pro M1) but when trying to build on Render.com i get the error in the screenshots below

![Screenshot 2023-05-09 at 18 44 56](https://github.com/mstephen19/nanolith/assets/70656399/6cd5ec6d-ca20-4316-ac06-4e801a855d81)
![Screenshot 2023-05-09 at 18 44 48](https://github.com/mstephen19/nanolith/assets/70656399/751f3c3b-f1ef-4759-b279-3e393b4f2ec2)

If you have any ideas about why this might be happening and how to fix that would be appreciated!

Thanks
Kez

**Comment by mstephen19** [comment]
Hey @Kezanwar! Sorry to get back to this so late. Did you end up finding a solution for this issue? And if so, what was the solution?

**Comment by Kezanwar** [comment]
> Hey @Kezanwar! Sorry to get back to this so late. Did you end up finding a solution for this issue? And if so, what was the solution?

Hi mate! No problem, there was no issue in the end, it was just that Render defaults to a lower version of NodeJS that doesn't support worker threads - the fix was just to specify the desired node version in my environment variables 😁

Thanks for your reply though and thanks for creating this pkg too!

**Comment by mstephen19** [comment]
Awesome! That's what I suspected. Thanks for sharing the solution to the problem, and thanks for supporting Nanolith 🔥
